### ISSUE TITLE
Permission denied fetching config file blows up the app

### ISSUE THREAD

**Issue by rsyring** [level12/keg#119]
We should treat this the same as file not found but log a warning.

```
Traceback (most recent call last):
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'someapp.celery' has no attribute 'worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someapp-beta/venv/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/app/utils.py", line 362, in find_app
    sym = imp(app)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/someapp-beta/src/someapp/celery/worker.py", line 19, in <module>
    someapp_app = someapp().init()
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/keg/app.py", line 88, in init
    self.init_config(config_profile, use_test_profile, config)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/keg/app.py", line 114, in init_config
    self.config.init_app(config_profile, self.import_name, self.root_path, use_test_profile)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/keg/config.py", line 73, in init_app
    self.config_file_objs = pymodule_fpaths_to_objects(possible_config_fpaths)
  File "/home/someapp-beta/venv_2019-04-30T19.40.48/lib/python3.6/site-packages/keg/utils.py", line 113, in pymodule_fpaths_to_objects
    if path.exists():
  File "/usr/lib/python3.6/pathlib.py", line 1336, in exists
    self.stat()
  File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/home/someapp-beta/.config/someapp/someapp-config.py'
Apr 30 23:52:20 shadow someapp-beta.uwsgi: [uwsgi-daemons] respawning "/home/someapp-beta/venv/bin/celery worker --app=someapp.celery.worker --queues=default --pidfile=/tmp/someapp-beta_celery.pid --workdir=/home/someapp-beta --concurrency=24 --max-memory-per-child=256000 --hostname=celery.shadow.level12.net" (uid: 1007 gid: 1005)
```

**Comment by guruofgentoo** [comment]
Handling in #106
