### ISSUE TITLE
Morphi throwing warnings about invalid resource paths

### ISSUE THREAD

**Issue by rsyring** [level12/keg#161]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rsyring/projects/keg-src/keg/__init__.py", line 6, in <module>
    from keg.app import Keg  # noqa: F401
  File "/home/rsyring/projects/keg-src/keg/app.py", line 9, in <module>
    from keg.blueprints import keg as kegbp
  File "/home/rsyring/projects/keg-src/keg/blueprints/__init__.py", line 5, in <module>
    from keg.extensions import lazy_gettext as _
  File "/home/rsyring/projects/keg-src/keg/extensions.py", line 13, in <module>
    translation_manager = Manager(package_name=MORPHI_PACKAGE_NAME)
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/morphi/messages/manager.py", line 26, in __init__
    self.locales = locales
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/morphi/messages/manager.py", line 47, in locales
    self.translations = self._translations_loader(self.dirname, self.locales,
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/morphi/messages/manager.py", line 103, in _translations_loader
    return load_translations(*args, **kwargs)
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/morphi/messages/manager.py", line 270, in load_translations
    mo_data = get_mo_data(dirname, locales, domain, package_name)
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/morphi/messages/manager.py", line 164, in get_mo_data
    mo_filename = find_mo_filename(localedir=dirname, languages=locales,
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/morphi/messages/manager.py", line 141, in find_mo_filename
    filename = gettext_find(attempted_domain, attempted_dirname, languages,
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/morphi/messages/manager.py", line 246, in gettext_find
    if path_exists(mofile):
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1391, in has_resource
    return self._has(self._fn(self.module_path, resource_name))
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1473, in _fn
    self._validate_resource_path(resource_name)
  File "/home/rsyring/projects/keg-src/.tox/py39-i18n/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1547, in _validate_resource_path
    warnings.warn(
DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
```

I added a filter to `pytest.ini` to ignore the warning and prevent errors during testing

**Comment by guruofgentoo** [comment]
I addressed this in morphi, released 0.2.1 there, and then removed the warning filter here.
